name: CI

permissions:
  contents: write

env:
  DOCKER_IMAGE: abhishekpatil1008/github-action-demo

on:
  push:
    branches:
      - main

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: build the docker image
        uses: docker/setup-buildx-action@v1

      - name: login to the docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.run_id }}
          platforms: linux/arm64,linux/amd64

  update-yaml:
    runs-on: ubuntu-latest
    needs: build-image-and-push
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Update tag in YAML
        run: |
          sed -i "s|image: .*|image: ${DOCKER_IMAGE}:${GITHUB_RUN_ID}|g" k8s/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "pythoncpp@gmail.com"
          git config --global user.name "Amit"
          git add k8s/deployment.yaml
          git commit -m "Update tag in deployment.yaml" || echo "No changes to commit"
          git push