# workflow name
name: First Workflow
# event
on: [push] 
# collection of jobs
jobs:
  # job name
    jobl:
      # runner
      runs-on: ubuntu-latest
      # steps to execute
      steps:
        # first step
          -name: hello world
          run: echo "hello world"